server:
  port: 80
  servlet:
    context-path: /consumer
spring:
  application:
    name: consumer-order-client
      
eureka:
  client:
    register-with-eureka: false
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/

logging:
  level:
    #feign日志以什么级别监控哪个接口
    com.lai.springcloud.service.PaymentFeignService: debug

  