server:
  port: 80
spring:
  application:
    name: consumer-order-client
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}


  