server:
  port: 8002
  servlet:
    context-path: /payment
  
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver  
    url: jdbc:mysql://localhost:3306/springclouddb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root1234
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lai.springcloud.entities    
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone: http://eureka7001.com:7001/eureka
  